version: '3'
services:
  backend:
    build: ./backend
    container_name: backend
    ports: 
      - 8080:8080
    volumes:
      - ./backend/app:/app
    stdin_open: true
    tty: true
    environment:
      FLASK_ENV: development
      MONGO_URI: mongodb://charmander:WYruavkTQrpddIf8@donatello-shard-00-00-weopu.mongodb.net:27017,donatello-shard-00-01-weopu.mongodb.net:27017,donatello-shard-00-02-weopu.mongodb.net:27017/test?ssl=true&replicaSet=Donatello-shard-0&authSource=admin&retryWrites=true&w=majority
      APP_ENV: QA
      # MONGO_URI: ds117145.mlab.com
      # MONGO_PORT: 17145
      # MONGO_DB: heroku_q03mkswf
      # MONGO_USER: charmander
      # MONGO_PW: 3235691ag
  # frontend:
  #   build: ./frontend
  #   container_name: frontend
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./frontend/app
  #     - ./frontend/app/node_modules
  #   depends_on:
  #     - 'backend'