version: '3'
services:
  backend:
    build: ./backend
    container_name: backend
    ports: 
      - 8080:8080
    volumes:
      - ./backend/app:/app
    stdin_open: true
    tty: true
    env_file:
      - ./.env
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/app
      - ./frontend/app/node_modules
    depends_on:
      - 'backend'