version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.development
    container_name: backend
    ports: 
      - 8080:8080
    volumes:
      - ./backend/app:/app
    stdin_open: true
    tty: true
    command: bash -c "python /app/app.py"
    env_file:
      - ./backend/.env.development.local
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env.development.local      
    depends_on:
      - 'backend'