version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    container_name: backend
    ports: 
      - 8080:8080
    volumes:
      - ./backend/app:/app
    command: bash -c "supervisord -n"
    env_file:
      - ./backend/.env.development.local
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env.production.local
    depends_on:
      - 'backend'